# Generated by Django 3.2.6 on 2022-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videosmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=12)),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
    ]
