# Generated by Django 3.2.6 on 2022-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchme', '0002_recentlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentlog',
            old_name='user',
            new_name='added_by',
        ),
    ]
