# Generated by Django 3.2.6 on 2022-11-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchme', '0003_rename_user_recentlog_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlog',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchme.adprofile'),
        ),
    ]
